In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')

In [2]:
dataset = pd.read_csv('binary_log.csv')

In [3]:
dataset

SAT Admitted  Gender
0    1363       No    Male
1    1792      Yes  Female
2    1954      Yes  Female
3    1653       No    Male
4    1593       No    Male
..    ...      ...     ...
163  1722      Yes  Female
164  1750      Yes    Male
165  1555       No    Male
166  1524       No    Male
167  1461       No    Male

[168 rows x 3 columns]

In [4]:
dataset['Admitted']=dataset['Admitted'].map({'No':0,'Yes':1})
dataset['Gender']=dataset['Gender'].map({'Male':0,'Female':1})

In [5]:
dataset

SAT  Admitted  Gender
0    1363         0       0
1    1792         1       1
2    1954         1       1
3    1653         0       0
4    1593         0       0
..    ...       ...     ...
163  1722         1       1
164  1750         1       0
165  1555         0       0
166  1524         0       0
167  1461         0       0

[168 rows x 3 columns]

In [6]:
X = dataset.iloc[:,[0,2]].values

In [7]:
X

array([[1363,    0],
       [1792,    1],
       [1954,    1],
       [1653,    0],
       [1593,    0],
       [1755,    1],
       [1775,    1],
       [1887,    1],
       [1893,    1],
       [1580,    0],
       [1857,    1],
       [1880,    1],
       [1664,    1],
       [1364,    0],
       [1693,    0],
       [1850,    1],
       [1633,    0],
       [1634,    0],
       [1636,    1],
       [1855,    1],
       [1987,    1],
       [1997,    0],
       [1422,    1],
       [1508,    1],
       [1720,    1],
       [1879,    0],
       [1634,    1],
       [1802,    0],
       [1849,    1],
       [1764,    1],
       [1460,    0],
       [1675,    1],
       [1656,    0],
       [2020,    0],
       [1850,    0],
       [1865,    0],
       [1664,    0],
       [1872,    1],
       [1654,    0],
       [1393,    1],
       [1587,    0],
       [1631,    1],
       [1931,    0],
       [1370,    0],
       [1810,    0],
       [1414,    0],
       [1761,    1],
       [1477,

In [8]:
y = dataset.iloc[:,1].values

In [9]:
y

array([0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0], dtype=int64)

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [12]:
X_train.shape

(134, 2)

In [13]:
X_test.shape

(34, 2)

In [14]:
from keras.models import Sequential
from keras.layers import Dense

In [15]:
model = Sequential()
model.add(Dense(8,activation='relu',input_dim=2))
model.add(Dense(8,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 8)                 24        
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 9         
Total params: 177
Trainable params: 177
Non-trainable params: 0
_________________________________________________________________


In [17]:
model.compile(loss='binary_crossentropy',optimizer='adam')

In [18]:
model.fit(X_train,y_train,epochs=100)

Epoch 1/100
5/5 [==============================] - 1s 4ms/step - loss: 259.0140
Epoch 2/100
5/5 [==============================] - 0s 4ms/step - loss: 237.0990
Epoch 3/100
5/5 [==============================] - 0s 4ms/step - loss: 216.6096
Epoch 4/100
5/5 [==============================] - 0s 6ms/step - loss: 195.6109
Epoch 5/100
5/5 [==============================] - 0s 4ms/step - loss: 177.1864
Epoch 6/100
5/5 [==============================] - 0s 4ms/step - loss: 159.5433
Epoch 7/100
5/5 [==============================] - 0s 6ms/step - loss: 141.8117
Epoch 8/100
5/5 [==============================] - 0s 4ms/step - loss: 125.4709
Epoch 9/100
5/5 [==============================] - 0s 4ms/step - loss: 109.1850
Epoch 10/100
5/5 [==============================] - 0s 6ms/step - loss: 93.3186
Epoch 11/100
5/5 [==============================] - 0s 6ms/step - loss: 79.4082
Epoch 12/100
5/5 [==============================] - 0s 4ms/step - loss: 64.0507
Epoch 13/100
5/5 [======================

In [19]:
y_pred = model.predict(X_test)

In [20]:
y_pred.round()

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)

In [21]:
y_test

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1], dtype=int64)